version: '3.8'
services:
  db:
    image: postgres:13
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: postgree_database
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data